---
title: "STAT 547M Homework 6"
author: "Tian Gao"
date: "Oct 30, 2018"
output: github_document
---

# Bring rectangular data in

```{r}
## load tidyverse
suppressPackageStartupMessages(library(tidyverse))
## load leaflet
suppressPackageStartupMessages(library(leaflet))
# install.packages("devtools")
#devtools::install_github("JoeyBernhardt/singer")
suppressPackageStartupMessages(library(singer))
## install ggmap
# devtools::install_github("dkahle/ggmap", ref = "tidyup")
## load ggmap
suppressPackageStartupMessages(library(ggmap))
## register API key (please do not use this key for any other purpose, thank you)
register_google(key = "AIzaSyDJnU2gOUgrDiIOSdujwanq9yX2yqRVlu4")


```

## Work with the`singer`data

# Task 4: Work with the `singer` data

* Use `purrr` to map latitude and longitude into human readable information on the band's origin places.

```{r}
# clean the data to delete the locations that have a value of NA
# here I only use the first 20 records to make the result clean
# The idea here can be used on the whole frame
cleaned_data <- singer_locations %>% 
  filter( !is.na(longitude)|!is.na(latitude)) %>%
  slice(1:20)
# convert the data to the readable version 
locations <- map2_chr(cleaned_data$longitude, cleaned_data$latitude, ~ revgeocode(as.numeric(c(.x, .y))))

## show the result
cbind(cleaned_data$city, locations) %>% 
  knitr::kable(col.names = c("city", "readable location"))
```

* Try to check wether the place in `city` corresponds to the information you retrieved.
```{r}
## first we need to find the city names
newcity<-cleaned_data %>% 
 select(city) %>% 
 separate(city,into = c("1","2","3"),sep=" ") 
#delete punctuation
newcity <- mapply(str_replace_all,newcity,",|-","") 
knitr::kable(newcity)

## second we need to extract the usel information from the city names
stringlocation <- as.character(locations)
newlocation <- str_extract_all(stringlocation[str_detect(stringlocation,"\\, [A-Z0-9].*[a-z]\\,|\\b[A-Z]{2,}\\b")],"\\, [A-Z0-9].*[a-z]\\,|\\b[A-Z]{2,}\\b",simplify = TRUE)
City <- str_replace_all(newlocation[,1],", |,", "")
newlocation[,1] = City
knitr::kable(newlocation)



result <- ((newlocation[,1]==newcity[,1])|(newlocation[,1]==newcity[,2])|(newlocation[,1]==newcity[,3])|(newlocation[,2]==newcity[,1])|(newlocation[,2]==newcity[,2])|(newlocation[,2]==newcity[,3])|(newlocation[,3]==newcity[,1])|(newlocation[,3]==newcity[,2])|(newlocation[,3]==newcity[,3]))
result

```

*  We can see that there are some false negative results like 53113 Bonn, Germany", "Bonn".